// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Docopt = require("docopt");

function parse(prim) {
  return Docopt.docopt(prim);
}

exports.parse = parse;
/* docopt Not a pure module */
