// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Preferences = require("preferences");

function Make() {
  var read = function (key, defaults, $staropt$star, namespace) {
    var encrypt = $staropt$star !== undefined ? $staropt$star : true;
    return new Preferences(namespace, defaults, {
                key: key,
                encrypt: encrypt
              });
  };
  return /* module */[/* read */read];
}

exports.Make = Make;
/* preferences Not a pure module */
