// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


function upgrade(stack, image) {
  console.log("Upgrading " + (stack + (" using " + image)));
  return /* () */0;
}

function upgradeFinish(stack, _) {
  console.log("Finishing upgrade of " + stack);
  return /* () */0;
}

function get(_, stack) {
  console.log("Getting compose file of " + stack);
  return /* () */0;
}

exports.upgrade = upgrade;
exports.upgradeFinish = upgradeFinish;
exports.get = get;
/* No side effect */
