// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function withOption(f, o) {
  if (o !== undefined) {
    return Curry._1(f, Js_primitive.valFromOption(o));
  } else {
    return /* () */0;
  }
}

exports.withOption = withOption;
/* No side effect */
